services:
  - type: web
    name: wasabi-url-api
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: WASABI_ACCESS_KEY
        sync: false
      - key: WASABI_SECRET_KEY
        sync: false
